using System.Text.RegularExpressions;
using System.Text;
using System.Text.Json;
using System.Net.Http.Headers;
using System.Diagnostics;
using TranskriptOkuyucu.Models;
using TranskriptOkuyucu.Services;

var options = new WebApplicationOptions
{
    Args = args,
    ContentRootPath = AppContext.BaseDirectory,
    WebRootPath = Directory.Exists(Path.Combine(AppContext.BaseDirectory, "wwwroot"))
        ? Path.Combine(AppContext.BaseDirectory, "wwwroot")
        : Path.Combine(Directory.GetCurrentDirectory(), "wwwroot")
};

var builder = WebApplication.CreateBuilder(options);
builder.WebHost.UseUrls("http://localhost:5240");

// Add services
builder.Services.AddMemoryCache();
builder.Services.AddHttpClient();
builder.Services.AddSingleton<IYouTubeTranscriptService, YouTubeTranscriptService>();
builder.Services.AddSingleton<IDocxExportService, DocxExportService>();
builder.Services.AddSingleton<IDictionaryService, DictionaryService>();

// Enable CORS for local development if needed
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod();
    });
});

var app = builder.Build();

app.UseCors();
app.UseDefaultFiles();
app.UseStaticFiles();

// Auto-open browser & friendly console banner on startup
app.Lifetime.ApplicationStarted.Register(() =>
{
    const string appUrl = "http://localhost:5240";
    Console.ForegroundColor = ConsoleColor.Cyan;
    Console.WriteLine();
    Console.WriteLine("╔══════════════════════════════════════════════════════════════╗");
    Console.WriteLine("║   🎬 YouTube Transkript Okuyucu Başarıyla Başlatıldı!        ║");
    Console.WriteLine("║   👉 Tarayıcınızda açın: http://localhost:5240               ║");
    Console.WriteLine("║   💡 Kapatmak için: Ctrl + C tuşlarına basın.                ║");
    Console.WriteLine("╚══════════════════════════════════════════════════════════════╝");
    Console.WriteLine();
    Console.ResetColor();

    try
    {
        if (OperatingSystem.IsWindows())
        {
            Process.Start(new ProcessStartInfo(appUrl) { UseShellExecute = true });
        }
        else if (OperatingSystem.IsMacOS())
        {
            Process.Start("open", appUrl);
        }
        else if (OperatingSystem.IsLinux())
        {
            Process.Start("xdg-open", appUrl);
        }
    }
    catch
    {
        // Browser open is a convenience, safe to ignore on failure
    }
});

// API: Get Video Info & Available Caption Tracks
app.MapPost("/api/video/info", async (VideoInfoRequest request, IYouTubeTranscriptService transcriptService) =>
{
    try
    {
        if (string.IsNullOrWhiteSpace(request.Url))
        {
            return Results.BadRequest(new { success = false, message = "Lütfen bir YouTube video linki girin." });
        }

        var metadata = await transcriptService.GetVideoMetadataAsync(request.Url);
        return Results.Ok(new { success = true, data = metadata });
    }
    catch (ArgumentException ex)
    {
        return Results.BadRequest(new { success = false, message = ex.Message });
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { success = false, message = "Video bilgileri alınırken hata oluştu: " + ex.Message });
    }
});

// API: Fetch Transcript for Video & Language
app.MapPost("/api/transcript/fetch", async (TranscriptFetchRequest request, IYouTubeTranscriptService transcriptService) =>
{
    try
    {
        if (string.IsNullOrWhiteSpace(request.Url))
        {
            return Results.BadRequest(new { success = false, message = "Lütfen bir YouTube video linki girin." });
        }

        var transcript = await transcriptService.GetTranscriptAsync(request.Url, request.LanguageCode, request.IsAutoGenerated);
        return Results.Ok(new { success = true, data = transcript });
    }
    catch (ArgumentException ex)
    {
        return Results.BadRequest(new { success = false, message = ex.Message });
    }
    catch (InvalidOperationException ex)
    {
        return Results.NotFound(new { success = false, message = ex.Message });
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { success = false, message = "Transkript alınırken hata oluştu: " + ex.Message });
    }
});

// API: Export Transcript to Word (.docx)
app.MapPost("/api/transcript/export-docx", (ExportDocxRequest request, IDocxExportService docxService) =>
{
    try
    {
        if (request.Items == null || request.Items.Count == 0)
        {
            return Results.BadRequest(new { success = false, message = "Dışa aktarılacak transkript verisi bulunamadı." });
        }

        var docxBytes = docxService.GenerateDocx(request);
        
        // Sanitize file name
        var safeTitle = string.Join("_", (request.Title ?? "Transkript").Split(Path.GetInvalidFileNameChars()));
        if (safeTitle.Length > 50) safeTitle = safeTitle[..50];
        var fileName = $"{safeTitle}_transkript.docx";

        return Results.File(
            docxBytes,
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            fileName
        );
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { success = false, message = "Word dosyası oluşturulurken bir hata oluştu: " + ex.Message });
    }
});

// API: Summarize Transcript using Gemini API
app.MapPost("/api/transcript/summarize", async (SummarizeRequest request, HttpClient httpClient) =>
{
    try
    {
        if (string.IsNullOrWhiteSpace(request.ApiKey))
        {
            return Results.BadRequest(new { success = false, message = "API Anahtarı eksik." });
        }

        if (string.IsNullOrWhiteSpace(request.TranscriptText))
        {
            return Results.BadRequest(new { success = false, message = "Özetlenecek metin bulunamadı." });
        }

        var prompt = "Aşağıdaki video transkriptini okuyarak ana fikirleri ve en önemli noktaları içeren, okunması kolay, maddeler halinde ve profesyonel bir dille Türkçe bir özet çıkar:\n\n" + request.TranscriptText;

        if (request.Provider == "OpenAI")
        {
            var requestBody = new
            {
                model = "gpt-4o-mini",
                messages = new[] { new { role = "user", content = prompt } }
            };

            var content = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");
            var requestMsg = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/chat/completions");
            requestMsg.Headers.Authorization = new AuthenticationHeaderValue("Bearer", request.ApiKey);
            requestMsg.Content = content;

            var response = await httpClient.SendAsync(requestMsg);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync();
                return Results.BadRequest(new { success = false, message = "OpenAI servisinden hata alındı." });
            }

            var jsonResponse = await response.Content.ReadAsStringAsync();
            using var doc = JsonDocument.Parse(jsonResponse);
            var summaryText = doc.RootElement
                .GetProperty("choices")[0]
                .GetProperty("message")
                .GetProperty("content")
                .GetString();

            return Results.Ok(new { success = true, data = summaryText });
        }
        else // Default to Gemini
        {
            var requestBody = new
            {
                contents = new[]
                {
                    new { parts = new[] { new { text = prompt } } }
                }
            };

            var content = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync($"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={request.ApiKey.Trim()}", content);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync();
                return Results.BadRequest(new { success = false, message = "Gemini servisinden hata alındı." });
            }

            var jsonResponse = await response.Content.ReadAsStringAsync();
            using var doc = JsonDocument.Parse(jsonResponse);
            var summaryText = doc.RootElement
                .GetProperty("candidates")[0]
                .GetProperty("content")
                .GetProperty("parts")[0]
                .GetProperty("text")
                .GetString();

            return Results.Ok(new { success = true, data = summaryText });
        }
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { success = false, message = "Özetleme işlemi sırasında bir hata oluştu: " + ex.Message });
    }
});

// API: Translate Transcript Line (MyMemory API)
app.MapPost("/api/transcript/translate", async (TranslateRequest request, HttpClient httpClient, IConfiguration config) =>
{
    try
    {
        if (string.IsNullOrWhiteSpace(request.TextToTranslate))
        {
            return Results.BadRequest(new { success = false, message = "Çevrilecek metin bulunamadı." });
        }

        var targetLang = string.IsNullOrWhiteSpace(request.TargetLanguage) ? "tr" : request.TargetLanguage;
        var encodedText = Uri.EscapeDataString(request.TextToTranslate);
        
        var email = config.GetValue<string>("TranslationConfig:Email");
        var deParam = string.IsNullOrWhiteSpace(email) ? "" : $"&de={email}";
        
        var url = $"https://api.mymemory.translated.net/get?q={encodedText}&langpair=autodetect|{targetLang}{deParam}";

        using var requestMessage = new HttpRequestMessage(HttpMethod.Get, url);
        requestMessage.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64)");

        var response = await httpClient.SendAsync(requestMessage);
        if (!response.IsSuccessStatusCode)
        {
            return Results.BadRequest(new { success = false, message = "Çeviri servisine ulaşılamadı." });
        }

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        
        var translatedText = string.Empty;
        
        if (doc.RootElement.TryGetProperty("responseData", out var responseData) && 
            responseData.TryGetProperty("translatedText", out var translatedTextElement))
        {
            translatedText = translatedTextElement.GetString();
        }

        if (string.IsNullOrWhiteSpace(translatedText))
        {
            translatedText = request.TextToTranslate;
        }

        return Results.Ok(new { success = true, data = translatedText });
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { success = false, message = "Çeviri işlemi sırasında bir hata oluştu: " + ex.Message });
    }
});

// API: Word / Term Dictionary Lookup (Meaning, Part of Speech, Definitions, Examples)
app.MapPost("/api/dictionary/lookup", async (DictionaryLookupRequest request, IDictionaryService dictionaryService) =>
{
    try
    {
        if (string.IsNullOrWhiteSpace(request.Word))
        {
            return Results.BadRequest(new { success = false, message = "Lütfen sorgulanacak bir kelime girin." });
        }

        var result = await dictionaryService.LookupWordAsync(request.Word, request.ApiKey, request.TargetLanguage ?? "tr");
        return Results.Ok(result);
    }
    catch (ArgumentException ex)
    {
        return Results.BadRequest(new { success = false, message = ex.Message });
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { success = false, message = "Sözlük sorgusu sırasında bir hata oluştu: " + ex.Message });
    }
});

app.Run();
