using TranskriptOkuyucu.Models.Transcript;

namespace TranskriptOkuyucu.Services;

public interface IYouTubeTranscriptService
{
    Task<VideoMetadataDto> GetVideoMetadataAsync(string url, CancellationToken cancellationToken = default);
    Task<TranscriptResultDto> GetTranscriptAsync(string url, string? languageCode = null, bool? isAutoGenerated = null, CancellationToken cancellationToken = default);
}
