using TranskriptOkuyucu.Models;

namespace TranskriptOkuyucu.Services;

public interface IYouTubeTranscriptService
{
    Task<VideoMetadataDto> GetVideoMetadataAsync(string url);
    Task<TranscriptResultDto> GetTranscriptAsync(string url, string? languageCode = null, bool? isAutoGenerated = null);
}
