using System.Net;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Caching.Memory;
using TranskriptOkuyucu.Models;
using YoutubeExplode;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;

namespace TranskriptOkuyucu.Services;

public class YouTubeTranscriptService : IYouTubeTranscriptService
{
    private readonly YoutubeClient _youtubeClient;
    private readonly IMemoryCache _cache;

    public YouTubeTranscriptService(IMemoryCache cache)
    {
        _youtubeClient = new YoutubeClient();
        _cache = cache;
    }

    public async Task<VideoMetadataDto> GetVideoMetadataAsync(string url)
    {
        var videoId = ExtractVideoId(url);
        var cacheKey = $"meta_{videoId.Value}";

        if (_cache.TryGetValue(cacheKey, out VideoMetadataDto? cachedMetadata) && cachedMetadata != null)
        {
            return cachedMetadata;
        }

        try
        {
            var video = await _youtubeClient.Videos.GetAsync(videoId);
            var manifest = await _youtubeClient.Videos.ClosedCaptions.GetManifestAsync(videoId);

            var tracks = manifest.Tracks
                .Select(t => new CaptionTrackDto(
                    LanguageCode: t.Language.Code,
                    LanguageName: string.IsNullOrWhiteSpace(t.Language.Name) ? t.Language.Code : t.Language.Name,
                    IsAutoGenerated: t.IsAutoGenerated
                ))
                .DistinctBy(t => new { t.LanguageCode, t.IsAutoGenerated })
                .OrderBy(t => t.IsAutoGenerated) // Manual tracks first
                .ThenBy(t => t.LanguageName)
                .ToList();

            var thumbnailUrl = video.Thumbnails
                .OrderByDescending(t => t.Resolution.Area)
                .FirstOrDefault()?.Url ?? $"https://img.youtube.com/vi/{videoId.Value}/maxresdefault.jpg";

            var durationStr = video.Duration.HasValue ? FormatTimeSpan(video.Duration.Value) : null;
            var durationSeconds = video.Duration?.TotalSeconds ?? 0;

            var result = new VideoMetadataDto(
                Id: videoId.Value,
                Title: video.Title,
                Author: video.Author.ChannelTitle,
                Duration: durationStr,
                DurationTotalSeconds: durationSeconds,
                ThumbnailUrl: thumbnailUrl,
                AvailableTracks: tracks
            );

            _cache.Set(cacheKey, result, TimeSpan.FromHours(2));
            return result;
        }
        catch (YoutubeExplode.Exceptions.YoutubeExplodeException ex)
        {
            throw new Exception("YOUTUBE_API_ERROR: YouTube API'sinde geçici bir sorun var veya istek limiti aşıldı. Lütfen daha sonra tekrar deneyin.", ex);
        }
        catch (HttpRequestException ex)
        {
            throw new Exception("YOUTUBE_API_ERROR: YouTube bağlantısı başarısız oldu. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.", ex);
        }
    }

    public async Task<TranscriptResultDto> GetTranscriptAsync(string url, string? languageCode = null, bool? isAutoGenerated = null)
    {
        var videoId = ExtractVideoId(url);
        var cacheKey = $"transcript_{videoId.Value}_{languageCode}_{isAutoGenerated}";

        if (_cache.TryGetValue(cacheKey, out TranscriptResultDto? cachedTranscript) && cachedTranscript != null)
        {
            return cachedTranscript;
        }

        try
        {
            var video = await _youtubeClient.Videos.GetAsync(videoId);
            var manifest = await _youtubeClient.Videos.ClosedCaptions.GetManifestAsync(videoId);

            if (manifest.Tracks.Count == 0)
            {
                throw new InvalidOperationException("Bu video için kullanılabilir herhangi bir altyazı veya transkript kaydı bulunamadı.");
            }

            ClosedCaptionTrackInfo? selectedTrack = null;

            // If specific language requested
            if (!string.IsNullOrWhiteSpace(languageCode))
            {
                if (isAutoGenerated.HasValue)
                {
                    selectedTrack = manifest.Tracks.FirstOrDefault(t =>
                        string.Equals(t.Language.Code, languageCode, StringComparison.OrdinalIgnoreCase) &&
                        t.IsAutoGenerated == isAutoGenerated.Value);
                }

                selectedTrack ??= manifest.Tracks.FirstOrDefault(t =>
                    string.Equals(t.Language.Code, languageCode, StringComparison.OrdinalIgnoreCase));
            }

            // Default selection strategy:
            // 1. Manual Turkish ("tr")
            // 2. Auto-generated Turkish ("tr")
            // 3. Manual English ("en")
            // 4. Any Manual track
            // 5. First available track
            if (selectedTrack == null)
            {
                selectedTrack = manifest.Tracks.FirstOrDefault(t => t.Language.Code.StartsWith("tr", StringComparison.OrdinalIgnoreCase) && !t.IsAutoGenerated)
                    ?? manifest.Tracks.FirstOrDefault(t => t.Language.Code.StartsWith("tr", StringComparison.OrdinalIgnoreCase))
                    ?? manifest.Tracks.FirstOrDefault(t => t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase) && !t.IsAutoGenerated)
                    ?? manifest.Tracks.FirstOrDefault(t => !t.IsAutoGenerated)
                    ?? manifest.Tracks.FirstOrDefault();
            }

            if (selectedTrack == null)
            {
                throw new InvalidOperationException("İstenen dilde altyazı bulunamadı.");
            }

            var track = await _youtubeClient.Videos.ClosedCaptions.GetAsync(selectedTrack);

            var transcriptItems = new List<TranscriptItemDto>();
            foreach (var caption in track.Captions)
            {
                var rawText = WebUtility.HtmlDecode(caption.Text ?? string.Empty).Trim();
                if (string.IsNullOrWhiteSpace(rawText))
                    continue;

                // Remove internal linebreaks to make smooth sentences
                var cleanText = Regex.Replace(rawText, @"\s+", " ");

                transcriptItems.Add(new TranscriptItemDto(
                    OffsetSeconds: caption.Offset.TotalSeconds,
                    DurationSeconds: caption.Duration.TotalSeconds,
                    TimestampFormatted: FormatTimeSpan(caption.Offset),
                    Text: cleanText
                ));
            }

            if (transcriptItems.Count == 0)
            {
                throw new InvalidOperationException("Altyazı dosyası indirildi fakat içinde metin satırı bulunamadı.");
            }

            var result = new TranscriptResultDto(
                VideoId: videoId.Value,
                Title: video.Title,
                Author: video.Author.ChannelTitle,
                LanguageCode: selectedTrack.Language.Code,
                LanguageName: string.IsNullOrWhiteSpace(selectedTrack.Language.Name) ? selectedTrack.Language.Code : selectedTrack.Language.Name,
                IsAutoGenerated: selectedTrack.IsAutoGenerated,
                Items: transcriptItems
            );

            _cache.Set(cacheKey, result, TimeSpan.FromHours(2));
            return result;
        }
        catch (YoutubeExplode.Exceptions.YoutubeExplodeException ex)
        {
            throw new Exception("YOUTUBE_API_ERROR: YouTube API'sinde geçici bir sorun var veya istek limiti aşıldı. Lütfen daha sonra tekrar deneyin.", ex);
        }
        catch (HttpRequestException ex)
        {
            throw new Exception("YOUTUBE_API_ERROR: YouTube bağlantısı başarısız oldu. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.", ex);
        }
    }

    private static VideoId ExtractVideoId(string url)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            throw new ArgumentException("Lütfen geçerli bir YouTube video linki girin.");
        }

        var parsed = VideoId.TryParse(url.Trim());
        if (parsed.HasValue)
        {
            return parsed.Value;
        }

        // Try fallback regex for custom embed or youtu.be links
        var match = Regex.Match(url, @"(?:youtu\.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]{11})");
        if (match.Success && match.Groups[1].Value.Length == 11)
        {
            var regexId = VideoId.TryParse(match.Groups[1].Value);
            if (regexId.HasValue) return regexId.Value;
        }

        throw new ArgumentException("Girilen bağlantı geçerli bir YouTube videosuna ait değil.");
    }

    private static string FormatTimeSpan(TimeSpan time)
    {
        if (time.TotalHours >= 1)
        {
            return $"{(int)time.TotalHours:D2}:{time.Minutes:D2}:{time.Seconds:D2}";
        }
        return $"{time.Minutes:D2}:{time.Seconds:D2}";
    }
}
