using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Caching.Memory;
using TranskriptOkuyucu.Common;
using TranskriptOkuyucu.Models.Transcript;
using YoutubeExplode;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;

namespace TranskriptOkuyucu.Services;

public partial class YouTubeTranscriptService : IYouTubeTranscriptService
{
    private readonly YoutubeClient _youtubeClient;
    private readonly IMemoryCache _cache;
    private readonly KeyedLock _keyedLock;

    public YouTubeTranscriptService(HttpClient httpClient, IMemoryCache cache, KeyedLock keyedLock)
    {
        _youtubeClient = new YoutubeClient(httpClient);
        _cache = cache;
        _keyedLock = keyedLock;
    }

    public async Task<VideoMetadataDto> GetVideoMetadataAsync(string url, CancellationToken cancellationToken = default)
    {
        var videoId = ExtractVideoId(url);
        var cacheKey = $"meta_{videoId.Value}";

        if (_cache.TryGetValue(cacheKey, out VideoMetadataDto? cachedMetadata) && cachedMetadata != null)
        {
            return cachedMetadata;
        }

        using (await _keyedLock.LockAsync(cacheKey, cancellationToken))
        {
            if (_cache.TryGetValue(cacheKey, out cachedMetadata) && cachedMetadata != null)
            {
                return cachedMetadata;
            }

            try
            {
                var video = await _youtubeClient.Videos.GetAsync(videoId, cancellationToken);
                var manifest = await _youtubeClient.Videos.ClosedCaptions.GetManifestAsync(videoId, cancellationToken);

                var tracks = manifest.Tracks
                    .Select(t => new CaptionTrackDto(
                        LanguageCode: t.Language.Code,
                        LanguageName: string.IsNullOrWhiteSpace(t.Language.Name) ? t.Language.Code : t.Language.Name,
                        IsAutoGenerated: t.IsAutoGenerated
                    ))
                    .DistinctBy(t => new { t.LanguageCode, t.IsAutoGenerated })
                    .OrderBy(t => t.IsAutoGenerated) // Manual tracks first
                    .ThenBy(t => t.LanguageName)
                    .ToList();

                var thumbnailUrl = video.Thumbnails
                    .OrderByDescending(t => t.Resolution.Area)
                    .FirstOrDefault()?.Url ?? $"https://img.youtube.com/vi/{videoId.Value}/maxresdefault.jpg";

                var durationStr = video.Duration.HasValue ? FormatTimeSpan(video.Duration.Value) : null;
                var durationSeconds = video.Duration?.TotalSeconds ?? 0;

                var result = new VideoMetadataDto(
                    Id: videoId.Value,
                    Title: video.Title,
                    Author: video.Author.ChannelTitle,
                    Duration: durationStr,
                    DurationTotalSeconds: durationSeconds,
                    ThumbnailUrl: thumbnailUrl,
                    AvailableTracks: tracks
                );

                _cache.Set(cacheKey, result, new MemoryCacheEntryOptions
                {
                    Size = 100, // Fixed weight for metadata
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(30)
                });
                return result;
            }
            catch (YoutubeExplode.Exceptions.YoutubeExplodeException ex)
            {
                throw new Exception("YOUTUBE_API_ERROR: YouTube API'sinde geçici bir sorun var veya istek limiti aşıldı. Lütfen daha sonra tekrar deneyin.", ex);
            }
            catch (HttpRequestException ex)
            {
                throw new Exception("YOUTUBE_API_ERROR: YouTube bağlantısı başarısız oldu. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.", ex);
            }
        }
    }

    public async Task<TranscriptResultDto> GetTranscriptAsync(string url, string? languageCode = null, bool? isAutoGenerated = null, CancellationToken cancellationToken = default)
    {
        var videoId = ExtractVideoId(url);
        var cacheKey = $"transcript_{videoId.Value}_{languageCode}_{isAutoGenerated}";

        if (_cache.TryGetValue(cacheKey, out TranscriptResultDto? cachedTranscript) && cachedTranscript != null)
        {
            return cachedTranscript;
        }

        using (await _keyedLock.LockAsync(cacheKey, cancellationToken))
        {
            if (_cache.TryGetValue(cacheKey, out cachedTranscript) && cachedTranscript != null)
            {
                return cachedTranscript;
            }

            try
            {
                var video = await _youtubeClient.Videos.GetAsync(videoId, cancellationToken);
                var manifest = await _youtubeClient.Videos.ClosedCaptions.GetManifestAsync(videoId, cancellationToken);

                if (manifest.Tracks.Count == 0)
                {
                    throw new InvalidOperationException("Bu video için kullanılabilir herhangi bir altyazı veya transkript kaydı bulunamadı.");
                }

                ClosedCaptionTrackInfo? selectedTrack = GetSelectedTrack(manifest, languageCode, isAutoGenerated);

                if (selectedTrack == null)
                {
                    throw new InvalidOperationException("İstenen dilde altyazı bulunamadı.");
                }

                var track = await _youtubeClient.Videos.ClosedCaptions.GetAsync(selectedTrack, cancellationToken);
                var forceHours = video.Duration?.TotalHours >= 1;

                var transcriptItems = MergeCaptionsIntoItems(track.Captions, forceHours);

                if (transcriptItems.Count == 0)
                {
                    throw new InvalidOperationException("Altyazı dosyası indirildi fakat içinde metin satırı bulunamadı.");
                }

                var result = new TranscriptResultDto(
                    VideoId: videoId.Value,
                    Title: video.Title,
                    Author: video.Author.ChannelTitle,
                    LanguageCode: selectedTrack.Language.Code,
                    LanguageName: string.IsNullOrWhiteSpace(selectedTrack.Language.Name) ? selectedTrack.Language.Code : selectedTrack.Language.Name,
                    IsAutoGenerated: selectedTrack.IsAutoGenerated,
                    Items: transcriptItems
                );

                _cache.Set(cacheKey, result, new MemoryCacheEntryOptions
                {
                    Size = transcriptItems.Count > 0 ? transcriptItems.Count : 1, // Weight based on transcript length
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(30)
                });
                return result;
            }
            catch (YoutubeExplode.Exceptions.YoutubeExplodeException ex)
            {
                throw new Exception("YOUTUBE_API_ERROR: YouTube API'sinde geçici bir sorun var veya istek limiti aşıldı. Lütfen daha sonra tekrar deneyin.", ex);
            }
            catch (HttpRequestException ex)
            {
                throw new Exception("YOUTUBE_API_ERROR: YouTube bağlantısı başarısız oldu. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.", ex);
            }
        }
    }

    private static ClosedCaptionTrackInfo? GetSelectedTrack(ClosedCaptionManifest manifest, string? languageCode, bool? isAutoGenerated)
    {
        ClosedCaptionTrackInfo? selectedTrack = null;

        if (!string.IsNullOrWhiteSpace(languageCode))
        {
            if (isAutoGenerated.HasValue)
            {
                selectedTrack = manifest.Tracks.FirstOrDefault(t =>
                    string.Equals(t.Language.Code, languageCode, StringComparison.OrdinalIgnoreCase) &&
                    t.IsAutoGenerated == isAutoGenerated.Value);
            }

            selectedTrack ??= manifest.Tracks.FirstOrDefault(t =>
                string.Equals(t.Language.Code, languageCode, StringComparison.OrdinalIgnoreCase));
        }

        if (selectedTrack == null)
        {
            selectedTrack = manifest.Tracks.FirstOrDefault(t => t.Language.Code.StartsWith("tr", StringComparison.OrdinalIgnoreCase) && !t.IsAutoGenerated)
                ?? manifest.Tracks.FirstOrDefault(t => t.Language.Code.StartsWith("tr", StringComparison.OrdinalIgnoreCase))
                ?? manifest.Tracks.FirstOrDefault(t => t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase) && !t.IsAutoGenerated)
                ?? manifest.Tracks.FirstOrDefault(t => !t.IsAutoGenerated)
                ?? manifest.Tracks.FirstOrDefault();
        }

        return selectedTrack;
    }

    private static List<TranscriptItemDto> MergeCaptionsIntoItems(IReadOnlyList<ClosedCaption> captions, bool forceHours)
    {
        var transcriptItems = new List<TranscriptItemDto>();
        double currentMergedStart = 0;
        double currentMergedDuration = 0;
        var currentMergedTextBuilder = new StringBuilder();
        bool hasCurrent = false;

        foreach (var caption in captions)
        {
            var rawText = WebUtility.HtmlDecode(caption.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(rawText))
                continue;

            var cleanText = SpacesRegex().Replace(rawText, " ");

            if (!hasCurrent)
            {
                currentMergedStart = caption.Offset.TotalSeconds;
                currentMergedDuration = caption.Duration.TotalSeconds;
                currentMergedTextBuilder.Append(cleanText);
                hasCurrent = true;
            }
            else
            {
                bool isSentenceEnd = CheckIfSentenceEnd(currentMergedTextBuilder);
                double gap = caption.Offset.TotalSeconds - (currentMergedStart + currentMergedDuration);
                bool isLongDuration = currentMergedDuration >= 6.0;

                if (!isSentenceEnd && gap < 1.5 && !isLongDuration)
                {
                    currentMergedTextBuilder.Append(" ").Append(cleanText);
                    currentMergedDuration = (caption.Offset.TotalSeconds + caption.Duration.TotalSeconds) - currentMergedStart;
                }
                else
                {
                    transcriptItems.Add(new TranscriptItemDto(
                        OffsetSeconds: currentMergedStart,
                        DurationSeconds: currentMergedDuration,
                        TimestampFormatted: FormatTimeSpan(TimeSpan.FromSeconds(currentMergedStart), forceHours),
                        Text: currentMergedTextBuilder.ToString().Trim()
                    ));

                    currentMergedStart = caption.Offset.TotalSeconds;
                    currentMergedDuration = caption.Duration.TotalSeconds;
                    currentMergedTextBuilder.Clear().Append(cleanText);
                }
            }
        }

        if (hasCurrent && currentMergedTextBuilder.Length > 0)
        {
            transcriptItems.Add(new TranscriptItemDto(
                OffsetSeconds: currentMergedStart,
                DurationSeconds: currentMergedDuration,
                TimestampFormatted: FormatTimeSpan(TimeSpan.FromSeconds(currentMergedStart), forceHours),
                Text: currentMergedTextBuilder.ToString().Trim()
            ));
        }

        return transcriptItems;
    }

    private static bool CheckIfSentenceEnd(StringBuilder sb)
    {
        if (sb.Length == 0) return false;

        char lastChar = sb[sb.Length - 1];
        if (lastChar == '\'' || lastChar == '"')
        {
            if (sb.Length > 1)
            {
                char secondLast = sb[sb.Length - 2];
                return secondLast == '.' || secondLast == '!' || secondLast == '?';
            }
        }
        return lastChar == '.' || lastChar == '!' || lastChar == '?';
    }

    private static VideoId ExtractVideoId(string url)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            throw new ArgumentException("Lütfen geçerli bir YouTube video linki girin.");
        }

        var parsed = VideoId.TryParse(url.Trim());
        if (parsed.HasValue)
        {
            return parsed.Value;
        }

        var match = YouTubeUrlRegex().Match(url);
        if (match.Success && match.Groups[1].Value.Length == 11)
        {
            var regexId = VideoId.TryParse(match.Groups[1].Value);
            if (regexId.HasValue) return regexId.Value;
        }

        throw new ArgumentException("Girilen bağlantı geçerli bir YouTube videosuna ait değil.");
    }

    private static string FormatTimeSpan(TimeSpan time, bool forceHours = false)
    {
        if (forceHours || time.TotalHours >= 1)
        {
            return $"{(int)time.TotalHours:D2}:{time.Minutes:D2}:{time.Seconds:D2}";
        }
        return $"{time.Minutes:D2}:{time.Seconds:D2}";
    }

    [GeneratedRegex(@"\s+")]
    private static partial Regex SpacesRegex();

    [GeneratedRegex(@"(?:youtu\.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]{11})")]
    private static partial Regex YouTubeUrlRegex();
}
