namespace TranskriptOkuyucu.Models.Transcript;

public record VideoInfoRequest(string Url);

public record TranscriptFetchRequest(string Url, string? LanguageCode = null, bool? IsAutoGenerated = null);

public record CaptionTrackDto(
    string LanguageCode,
    string LanguageName,
    bool IsAutoGenerated
);

public record VideoMetadataDto(
    string Id,
    string Title,
    string Author,
    string? Duration,
    double DurationTotalSeconds,
    string ThumbnailUrl,
    List<CaptionTrackDto> AvailableTracks
);

public record TranscriptItemDto(
    double OffsetSeconds,
    double DurationSeconds,
    string TimestampFormatted,
    string Text
);

public record TranscriptResultDto(
    string VideoId,
    string Title,
    string Author,
    string LanguageCode,
    string LanguageName,
    bool IsAutoGenerated,
    List<TranscriptItemDto> Items
);

public record ExportDocxRequest(
    string Title,
    string Author,
    string VideoUrl,
    string LanguageName,
    List<TranscriptItemDto> Items
);

public record TranslateRequest(
    string TextToTranslate,
    string? TargetLanguage = "tr"
);
