using Microsoft.AspNetCore.Mvc;
using TranskriptOkuyucu.Models.Common;
using TranskriptOkuyucu.Models.Transcript;
using TranskriptOkuyucu.Services;

using TranskriptOkuyucu.Infrastructure;
using TranskriptOkuyucu.Validations;

namespace TranskriptOkuyucu.Endpoints;

public static class TranscriptEndpoints
{
    public static IEndpointRouteBuilder MapTranscriptEndpoints(this IEndpointRouteBuilder app)
    {
        app.MapPost("/api/video/info", GetVideoInfoHandler)
           .AddEndpointFilter<ValidationFilter<VideoInfoRequest>>();
           
        app.MapPost("/api/transcript/fetch", FetchTranscriptHandler)
           .AddEndpointFilter<ValidationFilter<TranscriptFetchRequest>>();
           
        app.MapPost("/api/transcript/export-docx", ExportDocxHandler)
           .AddEndpointFilter<ValidationFilter<ExportDocxRequest>>();
           
        app.MapPost("/api/transcript/translate", TranslateTranscriptHandler)
           .AddEndpointFilter<ValidationFilter<TranslateRequest>>();

        return app;
    }

    private static async Task<IResult> GetVideoInfoHandler([FromBody] VideoInfoRequest request, [FromServices] IYouTubeTranscriptService transcriptService, CancellationToken ct)
    {

        var metadata = await transcriptService.GetVideoMetadataAsync(request.Url, ct);
        return Results.Ok(ApiResponse<VideoMetadataDto>.Ok(metadata));
    }

    private static async Task<IResult> FetchTranscriptHandler([FromBody] TranscriptFetchRequest request, [FromServices] IYouTubeTranscriptService transcriptService, CancellationToken ct)
    {

        var transcript = await transcriptService.GetTranscriptAsync(request.Url, request.LanguageCode, request.IsAutoGenerated, ct);
        return Results.Ok(ApiResponse<TranscriptResultDto>.Ok(transcript));
    }

    private static IResult ExportDocxHandler([FromBody] ExportDocxRequest request, [FromServices] IDocxExportService docxService)
    {

        var docxBytes = docxService.GenerateDocx(request);

        var safeTitle = string.Join("_", (request.Title ?? "Transkript").Split(Path.GetInvalidFileNameChars()));
        if (safeTitle.Length > 50) safeTitle = safeTitle[..50];
        var fileName = $"{safeTitle}_transkript.docx";

        return Results.File(
            docxBytes,
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            fileName
        );
    }

    private static async Task<IResult> TranslateTranscriptHandler([FromBody] TranslateRequest request, [FromServices] ITranslationService translationService, CancellationToken ct)
    {

        var targetLang = string.IsNullOrWhiteSpace(request.TargetLanguage) ? "tr" : request.TargetLanguage;
        var translatedText = await translationService.TranslateTextAsync(request.TextToTranslate, targetLang, ct);

        if (string.IsNullOrWhiteSpace(translatedText))
        {
            translatedText = request.TextToTranslate;
        }

        return Results.Ok(ApiResponse<string>.Ok(translatedText));
    }
}
