namespace TranskriptOkuyucu.Models;

public record VideoInfoRequest(string Url);

public record TranscriptFetchRequest(string Url, string? LanguageCode = null, bool? IsAutoGenerated = null);

public record CaptionTrackDto(
    string LanguageCode,
    string LanguageName,
    bool IsAutoGenerated
);

public record VideoMetadataDto(
    string Id,
    string Title,
    string Author,
    string? Duration,
    double DurationTotalSeconds,
    string ThumbnailUrl,
    List<CaptionTrackDto> AvailableTracks
);

public record TranscriptItemDto(
    double OffsetSeconds,
    double DurationSeconds,
    string TimestampFormatted,
    string Text
);

public record TranscriptResultDto(
    string VideoId,
    string Title,
    string Author,
    string LanguageCode,
    string LanguageName,
    bool IsAutoGenerated,
    List<TranscriptItemDto> Items
);

public record ExportDocxRequest(
    string Title,
    string Author,
    string VideoUrl,
    string LanguageName,
    List<TranscriptItemDto> Items
);

public record SummarizeRequest(
    string TranscriptText,
    string Provider,
    string ApiKey
);

public record TranslateRequest(
    string TextToTranslate,
    string? TargetLanguage = "tr"
);

public record DictionaryLookupRequest(
    string Word,
    string? TargetLanguage = "tr",
    string? ApiKey = null
);

public record DictionaryDefinitionDto(
    string Definition,
    string? Example
);

public record DictionaryEntryDto(
    string PartOfSpeech,
    string PartOfSpeechTr,
    List<string> Meanings,
    List<DictionaryDefinitionDto> Definitions,
    List<string> Synonyms
);

public record DictionaryLookupResponse(
    string Word,
    string PrimaryTranslation,
    string SourceLanguage,
    string TargetLanguage,
    List<DictionaryEntryDto> Entries,
    List<string> Examples,
    bool Success = true,
    string? Message = null,
    string? Phonetic = null,
    string? AudioUrl = null
);


